# Generated by Django 3.2 on 2021-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.CharField(max_length=200, verbose_name=(('jadibutti', 'jadibutti'), ('koteshwor', 'koteshwor'), ('lokanthali', 'lokanthali'), ('baneshwor', 'baneshwor'), ('ratnapark', 'ratnapark'), ('kandaghari', 'kandaghari'), ('thimi', 'thimi'), ('bagbazar', 'bagbazar'), ('chabahil', 'chabahil'), ('airport', 'airport'), ('pepsi', 'pepsi'))),
        ),
    ]
